---
title: "pig_cellranger"
output: html_document
date: "2023-07-17"
---

```{r setup, include=FALSE}
library(DropletUtils)
library(ggplot2)
library(scuttle)
library(Seurat)
```

## Load the data
```{r}
# load adult
pig.ad <- load_seurat("~/Desktop/count_matrix_pig/cellranger/Pig_adult/filtered_feature_bc_matrix",'adult_pig')
```

```{r}
# load E70
e70_s1 <- load_seurat("~/Desktop/count_matrix_pig/cellranger/pig_e70/SRR9705123/filtered_feature_bc_matrix",'e70_pig1')
e70_s2 <- load_seurat("~/Desktop/count_matrix_pig/cellranger/pig_e70/SRR9705124/filtered_feature_bc_matrix",'e70_pig2')
e70_s3 <- load_seurat("~/Desktop/count_matrix_pig/cellranger/pig_e70/SRR9705125/filtered_feature_bc_matrix",'e70_pig3')
e70_s4 <- load_seurat("~/Desktop/count_matrix_pig/cellranger/pig_e70/SRR9705126/filtered_feature_bc_matrix",'e70_pig4')
# merge four samples together
pig_e70 <- merge(e70_s1,y = c(e70_s2,e70_s3,e70_s4),add.cell.ids = c('1','2','3','4'),project = 'pig_e70')
```

## Data integration
```{r}
library(patchwork)
# Put object in a list
Int_pig_list <- list()
Int_pig_list[['Adult_nc']] <- pig_ad
Int_pig_list[['E70_nc']] <- pig_e70

# Normalize and find variable genes in each samples
Int_pig_list <- lapply(X=Int_pig_list, FUN=function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x,selection.method='vst')
})

# select features that are repeatedly variable across datasets for integration 
```

```{r}
# Perform integration
pig.anchors <- FindIntegrationAnchors(object.list = Int_pig_list,anchor.features = rownames(pig.ad))
# create integrated data assay
pig.integrated <- IntegrateData(anchorset = pig.anchors,features.to.integrate = rownames(pig.ad))
```
```{r}
# modfiy the sample names
pig.integrated$sample <- pig.integrated$orig.ident
pig.integrated$sample <- as.factor(pig.integrated$sample)
# Assign new labels to the levels
new_levels <- c("pig_adult","pig_E70","pig_E70","pig_E70","pig_E70")
# Update the levels of orig.ident
levels(pig.integrated$sample) <- new_levels
```

## QC
# remove high mitochardial genes
```{r}
# add 'percent.mt' value
DefaultAssay(pig.integrated) <- 'RNA'
pig.integrated[['percent.mt']] <- PercentageFeatureSet(pig.integrated, assay = 'RNA',pattern = '^MT-')
vln_pig<-VlnPlot(pig.integrated,features = c('nCount_RNA','nFeature_RNA','percent.mt'),ncol = 3,group.by = 'sample') 
```

```{r}
# remove the percent.mt > 10
# remove the number of gene > 4000, < 300
pig.integrated[["QC"]] <- ifelse(pig.integrated@meta.data$percent.mt > 10 | pig.integrated@meta.data$nFeature_RNA < 300 | pig.integrated@meta.data$nFeature_RNA > 4000,
'Fail','Pass')
pig.integrated <- subset(pig.integrated, subset = QC == 'Pass')
```


## Analysis the integrated data
```{r}
# do scaling and dimensionality reduction 
# using 30 dimensions
pig.integrated <- FindVariableFeatures(pig.integrated)
pig.integrated <- ScaleData(pig.integrated,verbose = FALSE)
pig.integrated <- RunPCA(pig.integrated,npcs=30,verbose=FALSE)
```


```{r}
elbow_pig<-ElbowPlot(pig.integrated,ndims = 30)
```

```{r}
# use 25 PCs
pig.integrated <- RunUMAP(pig.integrated,reduction='pca',dims = 1:25)
pig.integrated <- FindNeighbors(pig.integrated,reduction = 'pca',dims = 1:25)
pig.integrated <- FindClusters(pig.integrated,resolution = 0.8)
```

```{r}
# visaulization
# 20, 25, 29
cluster_pl_25 <- DimPlot(pig.integrated,reduction = 'umap',label = TRUE,repel = TRUE,group.by = 'seurat_clusters')
sample_pl <- DimPlot(pig.integrated,reduction = 'umap',repel = TRUE,group.by = 'sample')
sample_pl
```

```{r}
pig.batch <- DimPlot(pig.integrated,reduction = 'umap',repel = TRUE,group.by = 'sample') + theme_classic(base_size = 20)
```

# Cell type annotation
```{r}
# Create function
CellTypeAnnotionInt <- function(dataset, database, tissue) {
  gs_list = gene_sets_prepare(database, tissue)
  # get cell-type by cell matrix
  es.max = sctype_score(scRNAseqData = dataset[["integrated"]]@scale.data,
                        scaled = TRUE, gs = gs_list$gs_positive, gs2 = NULL) 
  # merge by cluster
  cL_resutls = do.call("rbind",
                       lapply(unique(dataset@meta.data$seurat_clusters),
                              function(cl){
                                es.max.cl =
                      sort(rowSums(es.max[,rownames(dataset@meta.data[dataset@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(dataset@meta.data$seurat_clusters==cl)), 10)
}))
  sctype_scores = cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores) 
  
  # set low-confident (low ScType score) clusters to "unknown"
  sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) <
                       sctype_scores$ncells/4] = "Unknown"
  print(sctype_scores[,1:3])
  
  dataset@meta.data$customclassif = ""
  for(j in unique(sctype_scores$cluster)){
  cl_type = sctype_scores[sctype_scores$cluster==j,]; 
  dataset@meta.data$customclassif[dataset@meta.data$seurat_clusters == j] =
    as.character(cl_type$type[1])
  }
  return(dataset)
}
```


```{r}
DefaultAssay(pig.integrated) <- 'integrated'
pig.integrated <- CellTypeAnnotionInt(pig.integrated,db_pig,tissue)
```
# visaulization
```{r}
#cell type umap plot
celltype_pig <- DimPlot(pig.integrated,reduction = 'umap',label = TRUE,repel = TRUE,group.by = 'customclassif')
```

```{r}
celltype_pig2 <- DimPlot(pig.integrated,reduction = 'umap',label = TRUE,repel = TRUE,group.by = 'customclassif')+theme_classic(base_size = 18) # make the legend bigger
```

```{r}
ct_overview <- pig.integrated@meta.data %>% select(sample , customclassif) %>% rename(dataset = sample) %>% group_by(dataset , customclassif) %>%
summarise(ncells = n()) %>%
ggplot () +
geom_bar(aes(customclassif , weight=ncells , fill=dataset)) + coord_flip() +theme_bw() + ylab('Number of cells') + xlab('Cell types') +theme_classic(base_size = 18)
```

## sub cell type
```{r}
Sub_set <- function(dataset, celltypename) {
  celltype <- as_tibble(dataset@meta.data) %>% dplyr::select(seurat_clusters,customclassif) %>% unique() %>% arrange(seurat_clusters) %>% filter(customclassif %in% c(celltypename))
  return(celltype)
}
p.sub.ex <- Sub_set(pig.integrated,'Excitatory neurons') 
ex.pig <- subset(pig.integrated, idents = p.sub.ex$seurat_clusters)
p.sub.in <- Sub_set(pig.integrated,'Inhibitory neurons') 
in.pig <- subset(pig.integrated, idents = p.sub.in$seurat_clusters)
```

